### ISSUE TITLE
Navigation bar doesn't touch the top of the screen

### ISSUE THREAD

**Issue by Samq64** [Samq64/samq64.github.io#1]
### Expected Behavior
The navigation bar should touch the top, left and right sides of the web page leaving no gaps.

### Actual Behavior
The navigation bar is padded all the way around it leaving gaps on the top, left and right sides of the web page.

![20210419_120043](https://user-images.githubusercontent.com/81489795/115267274-fd829000-a106-11eb-9d78-8aa4a556ddeb.jpg)

### Steps to Reproduce

Go to https://samq64.github.io and look at the top of the web page.
### Operating System and Browser

It effects all browsers and operating systems as far as I know.

**Comment by FunctionalMetatable** [comment]
setting `body`'s `margin` style to `0` should fix this.
```css
body {
  margin: 0;
}
```

**Comment by gosoccerboy5** [comment]
I'm guessing it's because you're for some reason using a [ul] element to wrap the header in which will automatically add some padding. I might be wrong.

**Comment by Samq64** [comment]
> I'm guessing it's because you're for some reason using a [ul] element to wrap the header in which will automatically add some padding. I might be wrong.

Yeah, probbably. Do you know how to remove the [ul] element without ruining the styling? Is there a different element I should be using instead?

**Comment by gosoccerboy5** [comment]
Honestly, idk. Maybe I'll inspect on Scratch's home page and see how they did it

**Comment by FunctionalMetatable** [comment]
try using `margin: 0` for the body instead i think

```css
body {
  margin: 0;
}
```

**Comment by gosoccerboy5** [comment]
> try using `margin: 0` for the body instead i think
> 
> ```css
> body {
>   margin: 0;
> }
> ```

That does seem to work, but I would only use margin: 0 on the header but not the rest of the page

**Comment by FunctionalMetatable** [comment]
> > try using `margin: 0` for the body instead i think
> > ```css
> > body {
> >   margin: 0;
> > }
> > ```
> 
> That does seem to work, but I would only use margin: 0 on the header but not the rest of the page

```css
margin-top: 0
```

**Comment by CodeGuy92** [comment]
My god. Just set the margin to 0px; and set .page's margin to however much you'd like.

```
<u>
Insert navbar here...
</u>
<div class="page">
Insert page content here...
</div>
```

**Comment by CodeGuy92** [comment]
> > > try using `margin: 0` for the body instead i think
> > > ```css
> > > body {
> > >   margin: 0;
> > > }
> > > ```
> > 
> > 
> > That does seem to work, but I would only use margin: 0 on the header but not the rest of the page
> 
> then use
> 
> ```css
> margin-top: 0;
> margin-left: 0;
> margin-right: 0; /* or something like that */
> ```

No. Dude. You need to define the measurement term. Use:
```
body {
  margin: 0px;
}
```

**Comment by CodeGuy92** [comment]
https://github.com/Samq64/samq64.github.io/pull/3

**Comment by Samq64** [comment]
Close
